[project]
name = "afridata-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chardet>=7.1.0",
    "django>=6.0.3",
    "djangorestframework>=3.16.1",
    "numpy>=2.4.2",
    "openpyxl>=3.1.5",
    "pandas>=3.0.1",
    "scikit-learn>=1.8.0",
    "sqlalchemy>=2.0.48",
    "xlrd>=2.0.2",
]
