[project]
name = "afridata-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anthropic>=0.84.0",
    "boto3>=1.42.74",
    "celery>=5.6.2",
    "chardet>=7.1.0",
    "django>=6.0.3",
    "djangorestframework>=3.16.1",
    "httpx>=0.28.1",
    "joblib>=1.5.3",
    "numpy>=2.4.2",
    "openai>=2.28.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.1",
    "python-dotenv>=1.2.2",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "sqlalchemy>=2.0.48",
    "xlrd>=2.0.2",
]
