# Generated by Django 6.0.3 on 2026-04-09 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('sql', 'SQL')], max_length=10)),
                ('source_path', models.TextField(blank=True, default='', help_text='File path (csv/excel) or table name (sql).')),
                ('dataset_title', models.CharField(blank=True, default='', max_length=255)),
                ('dataset_description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('elapsed_s', models.FloatField(blank=True, help_text='Total wall-clock seconds for the complete run.', null=True)),
                ('stage_times', models.JSONField(blank=True, help_text='Per-stage timing dict keyed by stage name.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pipeline Run',
                'verbose_name_plural': 'Pipeline Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetadataResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_schema', models.TextField(help_text='Pretty-printed JSON Schema draft-07.')),
                ('schema_dict', models.JSONField(help_text='Raw JSON Schema dict.')),
                ('schema_report', models.JSONField(default=dict, help_text='Diagnostic summary from SchemaBuilder.schema_report().')),
                ('column_count', models.PositiveIntegerField(default=0, help_text='Number of columns (properties) in the schema.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_result', to='metadata.pipelinerun')),
            ],
            options={
                'verbose_name': 'Metadata Result',
                'verbose_name_plural': 'Metadata Results',
            },
        ),
        migrations.CreateModel(
            name='ColumnProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('dtype', models.CharField(blank=True, default='', max_length=64)),
                ('semantic_type', models.CharField(blank=True, default='', max_length=128)),
                ('semantic_confidence', models.FloatField(blank=True, null=True)),
                ('nullable', models.BooleanField(default=False)),
                ('unique_count', models.PositiveIntegerField(blank=True, null=True)),
                ('null_count', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_data', models.JSONField(default=dict, help_text='Complete profile dict for this column from DataFrameProfiler.')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_profiles', to='metadata.pipelinerun')),
            ],
            options={
                'verbose_name': 'Column Profile',
                'verbose_name_plural': 'Column Profiles',
                'ordering': ['run', 'column_name'],
                'indexes': [models.Index(fields=['semantic_type'], name='metadata_co_semanti_f2d7c4_idx'), models.Index(fields=['run', 'semantic_type'], name='metadata_co_run_id_e0dd82_idx')],
                'unique_together': {('run', 'column_name')},
            },
        ),
    ]
