# Generated by Django 6.0.3 on 2026-04-09 15:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.IntegerField(db_index=True, help_text='PK of the source dataset record in the datasets app.', unique=True)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.TextField(blank=True, default='', help_text='Comma-separated tag slugs copied from the datasets app.')),
                ('category', models.CharField(blank=True, default='', help_text="Top-level category slug, e.g. 'health', 'finance'.", max_length=128)),
                ('organisation', models.CharField(blank=True, default='', max_length=256)),
                ('licence', models.CharField(blank=True, default='', max_length=64)),
                ('formats', models.CharField(blank=True, default='', max_length=128)),
                ('interaction_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'dataset proxy',
                'verbose_name_plural': 'dataset proxies',
                'ordering': ['-interaction_count'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranked_dataset_ids', models.JSONField(default=list, help_text='Ordered list of dataset PKs. Index 0 = top recommendation.')),
                ('scores', models.JSONField(default=list, help_text='Fused hybrid score for each ranked dataset ID.')),
                ('alpha', models.FloatField(default=0.5, help_text='Content-based weight in [0, 1]. 1 = pure content, 0 = pure CF.')),
                ('engine_used', models.CharField(choices=[('hybrid', 'Hybrid'), ('content_based', 'Content-Based Only'), ('collaborative', 'Collaborative Only'), ('fallback', 'Popularity Fallback')], default='hybrid', max_length=20)),
                ('candidate_pool_size', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_result', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.IntegerField(db_index=True, help_text='Primary key of the dataset in the datasets app table.')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('bookmark', 'Bookmark'), ('rating', 'Explicit Rating'), ('search_click', 'Search Click')], db_index=True, default='view', max_length=20)),
                ('explicit_rating', models.FloatField(blank=True, help_text='User-supplied rating (e.g. 1–5). Null for implicit interactions.', null=True)),
                ('dwell_seconds', models.PositiveIntegerField(default=0, help_text='Seconds spent on dataset page. 0 for non-view interactions.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'dataset_id'], name='recommendat_user_id_8318ef_idx'), models.Index(fields=['dataset_id', 'interaction_type'], name='recommendat_dataset_c7ab01_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'dataset_id', 'interaction_type'), name='unique_user_dataset_interaction_type')],
            },
        ),
    ]
