# Generated by Django 6.0.3 on 2026-06-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetproxy',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='timestamp',
        ),
    ]
